apiVersion: v1
entries:
  caddy:
  - annotations:
      artifacthub.io/changes: "- kind: changed\n  description: Bumped version "
      artifacthub.io/links: |
        - name: Caddy home
          url: https://github.com/caddyserver/caddy
    apiVersion: v2
    appVersion: 1.1.0
    created: "2026-04-27T12:02:08.644374+05:30"
    description: 'The Caddy web server is an extensible, cross-platform, open-source
      web server written in Go. '
    digest: b13d378890ac76950e9d2d07603da63cbd3f94ce7607adb1dfe24e8f6c2e91bb
    name: caddy
    type: application
    urls:
    - caddy-0.0.1.tgz
    version: 0.0.1
generated: "2026-04-27T12:02:08.642754+05:30"
